const mongoos=require("mongoose")

const orderSchema= new mongoos.Schema({
    userid:{
        type:String,
        required:true
    },
    Fullname:{
        type:String,
        required:true
    },
    mobile:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    longitude:{
        type:String,
        required:true
    },
    latitude:{
        type:String,
        required:true
    },
    area:{
        type:String,
        required:true
    },
    flat:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    pincode:{
        type:String,
        required:true
    },
    Status:{
        type:String,
        required:true
    },
    orderingDate:{
        type:Date,
        required:false
    },
    plan_year:{
        type:Number,
        required:false
    },
    paymentId:{
        type:String,
        required:false
    },
    payment_amount:{
        type:Number,
        required:false
    },
    completionDate:{
        type:Boolean,
        required:false
    },
    is_kyc_neede:{
        type:Boolean,
        required:true
    }
})

module.exports=mongoos.model('Order',orderSchema )