const { object } = require("joi")
const mongoos=require("mongoose")

const userSchema= new mongoos.Schema({
    userid:{
        type:String,
        required:true
    },
    Fullname:{
        type:String,
        required:true
    },
    mobile:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    longitude:{
        type:String,
        required:true
    },
    latitude:{
        type:String,
        required:true
    },
    area:{
        type:String,
        required:true
    },
    flat:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:true
    },
    state:{
        type:String,
        required:true
    },
    city:{
        type:String,
        required:true
    },
    pincode:{
        type:String,
        required:true
    },
    kycStatus:{
        type:Boolean,
        required:true
    },
    orderStatus:{
        type:Boolean,
        required:false
    },
    onBoardingDate:{
        type:Date,
        required:false
    },
    kycdata:{
        type:Object,
        required:false
    },
    devices:{
        type:Array,
        required:false
    },
    profileimage:{
        type:String,
        required:false
    },
    refferid:{
        type:String,
        required:false
    },
    gst:{
        type:String,
        required:false
    },
    companyname:{
        type:String,
        required:false
    }
})

module.exports=mongoos.model('User',userSchema )